### ISSUE TITLE
Eslint breaks with v5.10.0

### ISSUE THREAD

**Issue by AdrienLemaire** [marcelmokos/eslint-config-with-prettier#3]
When upgrading eslint from v5.9 to v5.10, it failed due to mandatory plugin eslint-plugin-dollar-sign that it cannot find.
Removing eslint-config-with-prettier seems to fix the issue.

Related issue: https://github.com/eslint/eslint/issues/11177

**Comment by AdrienLemaire** [comment]
eslint-config-with-prettier shouldn't have a dependency to jquery, we do not use it for our react project. Otherwise, please rename it as `eslint-jquery-config-with-prettier` and/or highlight the dependendency in the readme, thank you!

**Comment by marcelmokos** [comment]
Thanks for the ISSUE. 

I will remove the dependency, and make it optional in a readme.
